"use client";
import { useMemo, useState } from "react";
import { Panel } from "./ToolPage";
const bnDigits=["শূন্য","এক","দুই","তিন","চার","পাঁচ","ছয়","সাত","আট","নয়"];
const bnTens=["","","বিশ","ত্রিশ","চল্লিশ","পঞ্চাশ","ষাট","সত্তর","আশি","নব্বই"];
function under100(n:number){if(n<10)return bnDigits[n];if(n<20)return ["দশ","এগারো","বারো","তেরো","চৌদ্দ","পনেরো","ষোলো","সতেরো","আঠারো","উনিশ"][n-10];return bnTens[Math.floor(n/10)]+(n%10?" "+bnDigits[n%10]:"")}
function bnNumber(n:number){if(!Number.isFinite(n)||n<0||n>999999999)return "০ থেকে ৯৯,৯৯,৯৯,৯৯৯ পর্যন্ত পূর্ণসংখ্যা দিন";n=Math.floor(n);if(n<100)return under100(n);const parts:string[]=[];const crore=Math.floor(n/10000000);n%=10000000;const lakh=Math.floor(n/100000);n%=100000;const thousand=Math.floor(n/1000);n%=1000;const hundred=Math.floor(n/100);n%=100;if(crore)parts.push(under100(crore),"কোটি");if(lakh)parts.push(under100(lakh),"লাখ");if(thousand)parts.push(under100(thousand),"হাজার");if(hundred)parts.push(bnDigits[hundred],"শত");if(n)parts.push(under100(n));return parts.join(" ")}
export function CaseConverter(){const [text,setText]=useState("");const title=text.replace(/\w\S*/g,w=>w[0].toUpperCase()+w.slice(1).toLowerCase());const sentence=text.toLowerCase().replace(/(^|[.!?]\s+)([a-z])/g,(_,p,c)=>p+c.toUpperCase());return <Panel><h2 className="text-lg font-semibold">Case converter</h2><textarea value={text} onChange={e=>setText(e.target.value)} className="mt-3 min-h-32 w-full rounded-xl bg-white p-3 dark:bg-zinc-900" placeholder="Write English text..."/><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-4">{[["UPPER",text.toUpperCase()],["lower",text.toLowerCase()],["Title",title],["Sentence",sentence]].map(([label,value])=><button key={label} onClick={()=>setText(value)} className="rounded-xl bg-white p-2 text-sm hover:bg-zinc-200 dark:bg-zinc-900 dark:hover:bg-zinc-800">{label}</button>)}</div></Panel>}
export function BanglaNumberWords(){const [value,setValue]=useState("");const n=Number(value.replace(/,/g,""));return <Panel><h2 className="text-lg font-semibold">বাংলা সংখ্যা থেকে শব্দ</h2><input inputMode="numeric" value={value} onChange={e=>setValue(e.target.value)} placeholder="12345" className="mt-3 w-full rounded-xl bg-white p-3 dark:bg-zinc-900"/><div className="mt-3 min-h-14 rounded-xl bg-white p-3 dark:bg-zinc-900">{value?bnNumber(n):"ফলাফল এখানে দেখা যাবে"}</div></Panel>}
export function CsvTextTools(){const [text,setText]=useState("");const lines=useMemo(()=>text.split(/\r?\n/).filter(Boolean),[text]);const csv=lines.map(line=>line.split(",").map(cell=>"\""+cell.replaceAll("\"","\"\"")+"\"").join(",")).join("\n");return <Panel><h2 className="text-lg font-semibold">CSV / Text utility</h2><textarea value={text} onChange={e=>setText(e.target.value)} placeholder={"name,city\nSara,Khulna"} className="mt-3 min-h-40 w-full rounded-xl bg-white p-3 font-mono text-sm dark:bg-zinc-900"/><div className="mt-3 grid gap-2 sm:grid-cols-2"><div className="rounded-xl bg-white p-3 text-sm dark:bg-zinc-900">লাইন: {lines.length} · অক্ষর: {text.length}</div><button onClick={()=>navigator.clipboard.writeText(csv)} className="rounded-xl bg-zinc-400/10 p-3 text-sm hover:bg-zinc-400/25">Normalize CSV কপি</button></div></Panel>}
